name = "storail"
version = "1.0.0"
description = "A simple on-disc JSON based data store"

licences = ["Apache-2.0"]
repository = { type = "github", user = "", repo = "" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 3.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
decode = ">= 0.3.0 and < 1.0.0"
directories = ">= 1.1.0 and < 2.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
gleam_crypto = ">= 1.4.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
